spring:
  rabbitmq:
    addresses: 192.168.150.129:5672
    username: guest
    password: guest
    host: /
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        prefetch: 1
server:
  port: 8002
  servlet:
    context-path: /coustomer

